version: "2"
services:
  exigent-backend:
    build: .
    ports:
      - "80:3000"
    command: "npm start:prod"
    environment: 
      - MONGO_URI=mongodb://exigent-db:27017/exigent-db
      - UPLOAD_DEST=/usr/uploads
  exigent-db:
    image: mongo
    ports:
      - "27017:27017"